# Generated by Django 3.0.2 on 2020-01-13 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Widget Title')),
                ('active', models.BooleanField(blank=True, verbose_name='Activate Widget')),
            ],
            options={
                'verbose_name': 'Dashboard Widget',
                'verbose_name_plural': 'Dashboard Widgets',
            },
        ),
        migrations.CreateModel(
            name='RSSFeedWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='RSS Url')),
                ('widget', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='widget', to='dashboardfeeds.DashboardWidget', verbose_name='widget')),
            ],
            options={
                'verbose_name': 'RSS Widget',
                'verbose_name_plural': 'RSS Widgets',
            },
        ),
    ]
