# Generated by Django 3.0.2 on 2020-01-13 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardfeeds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='base_url',
            field=models.URLField(default='example.com', help_text='index url of the news website (as link for users)', verbose_name='Base URL'),
            preserve_default=False,
        ),
    ]
